name: Test R-universe

on:
  push:
    branches: [main, master]
    paths:
      - .github/workflows/r-universe-test.yml
      - .Rbuildignore
      - DESCRIPTION
      - NAMESPACE
      - R/**
      - src/**
      - tests/**
      - vignettes/**
      - man/**
  pull_request:
    branches: [main, master]
    paths:
      - .github/workflows/r-universe-test.yml
      - .Rbuildignore
      - DESCRIPTION
      - NAMESPACE
      - R/**
      - src/**
      - tests/**
      - vignettes/**
      - man/**
  workflow_dispatch:

jobs:
  build:
    name: R-universe Test
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}